adapter:
  version_file_relative_path: 'version.rb'
  version_field: 'VERSION'
  version_type: 'semver'
  adapter_name: 'custom'

vcs:
  provider: gitlab
  base_url: 'https://mygitlab.com/api/v3/projects'